### ISSUE TITLE
依頼　フリマアプリの挙動確認

### ISSUE THREAD

**Issue by rkrstl** [rkrstl/furima_28696#10]
herokuのURL
https://furima-28696.herokuapp.com/

ユーザー名
admin
パスワード
2222

出品者
hamu@gmail.com
パスワード rika0714

購入可能な別のユーザ
choiihwa68@gmail.com
パスワード　rika0714

PAY.JPのテストカード情報
カード番号 4242424242424242（16桁）
CVC 123
有効期限 登録時より未来

**Comment by tnk1215** [comment]
rkrstl さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下２点の不備が見受けられましたので修正をお願いします！
修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

[修正箇所]
**①　挙動確認にあたっての必要な情報の記載をお願いします。**
→「出品者用のパスワード」「購入者用パスワード」「購入用カードの有効期限」の記載がないため出品〜購入に関する挙動確認ができません。記載いただき再度ご依頼をお願いします。
（必要記入事項は画像参照）
<img width="727" alt="スクリーンショット 2020-09-09 14 07 27" src="https://user-images.githubusercontent.com/63444423/92557058-5a32e800-f2a6-11ea-8807-dd1b9aeda9ca.png">

**②　商品詳細画面の「税込」が二重で表示されている**
→　こちら一つでよろしいかと思います。修正をお願いします。
<img width="197" alt="スクリーンショット 2020-09-09 14 10 22" src="https://user-images.githubusercontent.com/63444423/92557076-6028c900-f2a6-11ea-8749-eca8282e4132.png">

--

**Comment by sho0127** [comment]
rkrstlさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
「必要情報を全て入力した上で購入ボタンを押した結果、下記のエラーメッセージが表示された」
<img width="611" alt="スクリーンショット 2020-09-09 15 54 03" src="https://user-images.githubusercontent.com/68053333/92564973-f7951880-f2b4-11ea-9c84-92d80b47d713.png">

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by rkrstl** [comment]
> rkrstlさん、ご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> 
> [修正箇所]
> 「必要情報を全て入力した上で購入ボタンを押した結果、下記のエラーメッセージが表示された」
> <img alt="スクリーンショット 2020-09-09 15 54 03" width="611" src="https://user-images.githubusercontent.com/68053333/92564973-f7951880-f2b4-11ea-9c84-92d80b47d713.png">
> 
> 修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
> https://forms.gle/dYuR1wjeHepbEhU7A
